---

- name: Clone a virtual machine from Linux template and customize
  vmware_guest:
    hostname: "{{ vm_vcenter_host | default(lookup('env', 'VMWARE_HOST')) }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vm_vcenter_datacenter }}"
    cluster: "{{ vm_vcenter_cluster }}"
    state: present
    folder: "{{ vm_vcenter_folder }}"
    template: "{{ vm_vcenter_template }}"
    name: "{{ inventory_hostname }}"
    disk: "{{ disk.disks }}"
    hardware:
      hotadd_cpu: True
      hotadd_memory: True
      memory_mb: "{{ vm_ram }}"
      num_cpus: "{{ vm_num_cpus }}"
    networks:
      - name: "{{ vm_eth0_network }}"
        ip: "{{ vm_eth0_ip }}"
        netmask: "{{ vm_eth0_mask }}"
        gateway: "{{ vm_eth0_gw }}"
        dvswitch_name: "{{ vm_vcenter_vds }}"
        device_type: "{{ vm_eth0_device }}"
        start_connected: "{{ vm_vcenter_net_connected }}"
      - name: "{{ vm_eth1_network }}"
        ip: "{{ vm_eth1_ip }}"
        netmask: "{{ vm_eth1_mask }}"
        gateway: "{{ vm_eth1_gw }}"
        dvswitch_name: "{{ vm_vcenter_vds }}"
        device_type: "{{ vm_eth1_device }}"
        start_connected: "{{ vm_vcenter_net_connected }}"
    wait_for_ip_address: True
    customization:
      hostname:
      - "{{ vm_hostname | default(inventory_hostname) }}"
      dns_servers:
      - "{{ vm_dns_server }}"
      dns_suffix:
      - "{{ vm_dns_suffix }}"
    wait_for_customization: True
  delegate_to: localhost
